name: Una Kravets Online
description: Front-end development and design musings
url: https://una.im
enforce_ssl: una.im
markdown: kramdown
highlighter: pygments.rb # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
github_username:  una
plugins: [jekyll-paginate]
paginate: 5
future: true
permalink: pretty
