name: Almost Profound
description: Front end development and design musings
url: http://una.im
markdown: kramdown
highlighter: pygmentize # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
kramdown:
  input: GFM
twitter_username: una
github_username:  una
paginate: 5
gems: ["jekyll-paginate"]