name: Almost Profound
description: Front end development and design musings
url: http://una.im
markdown: redcarpet
highlighter: pygmentize # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
twitter_username: una
github_username:  una
paginate: 5
gems: ["jekyll-paginate"]
future: true